# verbose: print some extra information while running.
verbose: True

# If true, figures will be generated and saved to PNG files
figures: True

# Filename prefix for saved data.
# Make sure any path used exists.
sim_name: out/henon_heiles

# Grid parameters. n = number of
# points in each direction, should be power of 2.
# 2L = box size, i.e., domain is [-L,L]**3.
grid:
  n: 512
  L: 12

particles:
  m: 10.0

# Set up model potential.
potential:
#  U: 'lambda x, y: (x**2 + y**2 + 0.1)**(-0.5)' 
  ell: .111806

initial:
  x0: 0.25
  y0: 0.5
  px0: -10.0
  py0: 0.0
  sigma0: 3.0

# Set up integration parameters.
# t_final: end of simulation time interval
# dt: time step
# n_inspect: number of inspections of densities over
# the simulation interval
# n_save: number of full wavefunction saves.
integration:
  t_final: 100.0
  dt: 0.01
  n_inspect: 100
  n_save: 1000
